### ISSUE TITLE
You may try again now and Fooocus will download models again

### ISSUE THREAD

**Issue by FrankYoungchen** [WHU-USI3DV/VistaDream#1]
when `python demo.py`, it will 
![image](https://github.com/user-attachments/assets/2379787d-2810-4db0-9235-020ec9caacd8)

**Comment by HpWang-whu** [comment]
Hi @FrankYoungchen,
I am sorry for the issue with the Fooocus weights download command in download_weights.sh. I have corrected this error based on [this issue](https://github.com/lllyasviel/Fooocus/issues/1045). You might solve this error by manually download the required weights:
- Download inpaint model [here](https://huggingface.co/lllyasviel/fooocus_inpaint/resolve/main/inpaint_v26.fooocus.patch) and save it to ```tools/Fooocus/models/inpaint```.
- Download unscale_models model [here](https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_upscaler_s409985e5.bin) and save it to ```tools/Fooocus/models/unscale_models```.
- Download Prompt-Extension [here](https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_expansion.bin), rename it to ```pytorch_model.bin``` and save it to ```tools/Fooocus/models/prompt_expansion/fooocus_expansion/```.

If you encounter any other issues, please feel free to let me know.

Yours,

**Comment by camenduru** [comment]
Hi 👋 is this ckpt https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_base_1.0.safetensors ?

https://github.com/WHU-USI3DV/VistaDream/blob/232379c5ab50418453f96e9cc3c75be325ee1f07/ops/mcs.py#L23-L24
