### ISSUE TITLE
More types of trajectories coming SOON.

### ISSUE THREAD

**Issue by HpWang-whu** [WHU-USI3DV/VistaDream#11]
TODO: Allow users to select more types of trajectories.
A 360-Degree-Rot-Traj example is shown below. Thank Hongjie Li @Geo-Tell for this video.

https://github.com/user-attachments/assets/d72b6505-0853-455e-a714-f0b45aea6334

**Comment by keyonchrist** [comment]
This is cool, whens that coming? I'm trying out some trajectories myself too

**Comment by HpWang-whu** [comment]
Hi @keyonchrist ,
Thanks for your interest! I will update it and some other features at about December.

Yours,

**Comment by Daibo-Baby** [comment]
> This is cool, whens that coming? I'm trying out some trajectories myself too

**You can just add a new python file in path "VistaDream/ops/trajs/", you can call it "rot.py", and then you can just write the
code in Funciton: generate_rot_trajectory like this:**
```python
def generate_rot_trajectory(num_frames, radius):
    t = np.linspace(0, 1, num_frames)
    r = radius
    # rotation angles at each frame
    theta = 2 * np.pi * t
    # try not to change y (up-down for floor and sky)
    x = r * np.cos(theta)
    y = np.full(num_frames, 0)
    z = r * np.sin(theta)
    return x, y, z 
```
**And you can just keep the other things in the same as the file in: "VistaDream/ops/trajs/spiral.py"**
