### ISSUE TITLE
Text prompt editing

### ISSUE THREAD

**Issue by keyonchrist** [WHU-USI3DV/VistaDream#13]
is there a simple way to edit the weight of the text prompt that is generated for inpainting/outpainting? Sometimes I find its better to let the model hallucinate than try to create too much detail. Thank you, and amazing work!

**Comment by HpWang-whu** [comment]
Hi @keyonchrist ,
You could try adjusting the control parameters of Fooocus in ```tools/Fooocus/fooocus_command.py```, such as [here](https://github.com/WHU-USI3DV/VistaDream/blob/5305b46d229c058594d3566f832e3b003d1e08e9/tools/Fooocus/fooocus_command.py#L47), as these are currently set to default values.

Yours,
