### ISSUE TITLE
Sparse-multiview-input supporting comes soon!

### ISSUE THREAD

**Issue by HpWang-whu** [WHU-USI3DV/VistaDream#14]
TODO: Allow users to input more views and no poses are needed. This feature will be updated at about December.
An example result of VistaDream with two unposed images as input are shown below.

Inputs:
![frame-001820](https://github.com/user-attachments/assets/6947c7f0-210f-45e3-91de-59fb64c38482)
![frame-002025](https://github.com/user-attachments/assets/2b32d2ec-b4eb-4728-b516-c2240b4af7ab)

RGB renderings from the scene reconstructed with VistaDream:

https://github.com/user-attachments/assets/70f4b0be-bb26-4b00-9764-15e87380edf3

**Comment by yqdch** [comment]
Cool, if this video was rendered using optimized 3DGS

**Comment by HpWang-whu** [comment]
New Demo with three input views.
Inputs:

![Image](https://github.com/user-attachments/assets/1b8be01c-7a8b-4362-b163-f08ff14b4a53)
![Image](https://github.com/user-attachments/assets/06358c74-ec04-4010-a043-93c310af4c97)
![Image](https://github.com/user-attachments/assets/475cb3ea-fe08-417e-888e-d0b7e6e2e5e1)

RGB renderings from the scene reconstructed with VistaDream:

https://github.com/user-attachments/assets/ed570480-0071-4e0e-8942-bc703ae77f4b
