### ISSUE TITLE
How to extend to cross-view scene reconstruction

### ISSUE THREAD

**Issue by sukirk** [WHU-USI3DV/VistaDream#17]
I wish you the best of luck with your work—it deserves to be accepted!
Your research shows great promise in single-view scene reconstruction near the original view, and I would like to see it extended to cross-view reconstruction. I found the trajectory generation code in  `ops/trajs/__init__.py`.
![image](https://github.com/user-attachments/assets/4df567ea-d832-4b8b-b6bb-14e77b6092f3)

Figure (a) is my understanding of spiral trajectory generation, but I am aiming to implement the trajectory depicted in Figure (b). To achieve this, I have developed the following trajectory generation function:
```python
import numpy as np

def generate_xz_trajectory(num_frames, swing_radius, target_depth):
    t = np.linspace(0, 1, num_frames) * 2*np.pi
    y = -target_depth*np.ones((num_frames,))
    x = swing_radius * np.cos(t)
    z = target_depth + swing_radius * np.sin(t)
    return x, y, z

def look_at(camera_position, target_position):
    # look at direction
    direction = target_position - camera_position
    direction /= np.linalg.norm(direction)
    # calculate rotation matrix
    up = np.array([0, 1, 0])
    right = np.cross(up, direction)
    right /= np.linalg.norm(right)
    up = np.cross(direction, right)
    rotation_matrix = np.vstack([right, up, direction])
    rotation_matrix = np.linalg.inv(rotation_matrix)
    return rotation_matrix

def xz_camera_poses(num_frames, radius, look_at_times = 0.5):
    target_depth = radius*look_at_times
    x, y, z = generate_xz_trajectory(num_frames, 0.02, target_depth)
    target_position = np.array([0,0,target_depth])
    camera_positions = np.vstack([x, y, z]).T
    camera_poses = []
    
    for pos in camera_positions:
        rotation_matrix = look_at(pos, target_position)
        transform_matrix = np.eye(4)
        transform_matrix[:3, :3] = rotation_matrix
        transform_matrix[:3,  3] = pos
        camera_poses.append(transform_matrix[None])
        
    camera_poses.reverse()
    camera_poses = np.concatenate(camera_poses,axis=0)
    
    return camera_poses
```
However, the video generated using our trajectory still contains many black voids that the diffusion model is not correctly handling. This may be due to a wrong implementation of my trajectory generation, or it may be necessary to adjust certain configurations in `pipe/cfgs/basic.yaml`.

My test case is the `readingroom` scene. I would greatly appreciate any guidance you could provide.

Thank you!

**Comment by HpWang-whu** [comment]
Hi @gasharper ,
Many thanks for your encouragement! I have updated the feature o trajectory design. You can re-pull the repo and design&check your trajectory following [here](https://github.com/WHU-USI3DV/VistaDream/blob/main/ops/trajs/TRAJECTORY.MD).

I suggest avoiding such a large view-change. Instead, it would be better to gradually transition towards a downward-looking perspective.

Yours.

**Comment by pique2233** [comment]
May I ask how your work on Vistadream-based cross-view reconstruction is progressing? I am planning to work on the same recently and improve on the depth processing
