### ISSUE TITLE
the wobble trajectory code is error

### ISSUE THREAD

**Issue by GaryW666** [WHU-USI3DV/VistaDream#18]
hi，the wobble trajectory code is the same as the sprial trajectory's，would you update the right code？Thank you.
![img_v3_02hg_37a5800e-82d8-4c9b-8e20-0276119675ag](https://github.com/user-attachments/assets/acd02b25-555a-4923-a912-077b3df5581a)

**Comment by HpWang-whu** [comment]
Thanks for that and I have already corrected the annotation error.
