### ISSUE TITLE
Noise in teaser gif

### ISSUE THREAD

**Issue by raven38** [WHU-USI3DV/VistaDream#2]
Thank you for sharing your excellent work.
You can reduce the noise in teaser gif by using this command. 
`ffmpeg -i input.mov -filter_complex "[0:v] fps=10,scale=640:-1,split [a][b];[a] palettegen [p];[b][p] paletteuse" output.gif`

**Comment by HpWang-whu** [comment]
Many thanks for your kind suggestion! I have regenerate it!
