### ISSUE TITLE
Script to generate image with specific camera view

### ISSUE THREAD

**Issue by raul678** [WHU-USI3DV/VistaDream#3]
Is there any script to generate image with specific camera view? or an interactive demo like GenWarp? Thanks.

**Comment by HpWang-whu** [comment]
Hi @raul678,
At now you can render RGB-D images from the reconstructed scene following [here](https://github.com/WHU-USI3DV/VistaDream/blob/537aa5c11a68e87491fdc8d8fd7c953928f896df/ops/visual_check.py#L43-L50).
We will develop a interactive demo ASAP and consider to fullfill the requirement. 

Yours,

**Comment by raul678** [comment]
> Hi @raul678, At now you can render RGB-D images from the reconstructed scene following [here](https://github.com/WHU-USI3DV/VistaDream/blob/537aa5c11a68e87491fdc8d8fd7c953928f896df/ops/visual_check.py#L43-L50). We will develop a interactive demo ASAP and consider to fullfill the requirement.
> 
> Yours,

Thanks. For some scenes, it shows the images are blurry. This is correct result? 
![1](https://github.com/user-attachments/assets/f400197a-e666-4ea4-8fcb-49f1fa2626e3)
![2](https://github.com/user-attachments/assets/66a66c8f-f358-4d7f-8791-6130f85a68f8)

**Comment by HpWang-whu** [comment]
Currently, depth estimation based on Depth Pro may show abrupt changes in the window regions of some images, which can also affect the completion results in other areas. You can try adjusting the scene generation control parameters [here](https://github.com/WHU-USI3DV/VistaDream/blob/5edde3dfe359fad7226650301fd7327c39463b81/pipe/cfgs/basic.yaml#L33-L36) to improve the outcome. For example, the result below is reconstucted by setting ```far_percentage``` to 70 and ```traj_forward_ratio``` to 0.8. We will address this issue in future updates.

https://github.com/user-attachments/assets/3fcca92d-c5f2-4ecf-af45-78bf6eea3a28

**Comment by keyonchrist** [comment]
> here

hey! were you able to download the images? I can't seem to get it to work like that. Also for depth, I'm looking at using lotus for depth instead of depth pro, it could help a lot with the windows blurring
