### ISSUE TITLE
Oneformer Checkpoint Directory Mismatch

### ISSUE THREAD

**Issue by HashingTag** [WHU-USI3DV/VistaDream#5]
There is a mismatch between the file download directory and the load directory [here](https://github.com/WHU-USI3DV/VistaDream/blob/537aa5c11a68e87491fdc8d8fd7c953928f896df/download_weights.sh#L23) and [here](https://github.com/WHU-USI3DV/VistaDream/blob/537aa5c11a68e87491fdc8d8fd7c953928f896df/pipe/cfgs/basic.yaml#L7).

**Comment by HpWang-whu** [comment]
I am really sorry for the issue caused by my carelessness and I have corrected it. If you encounter any other issues, please feel free to let me know.
