### ISSUE TITLE
issue about loss

### ISSUE THREAD

**Issue by micky-li-hd** [WHU-USI3DV/VistaDream#9]
Hello @HpWang-whu ！
i would ask the question that:[here](https://github.com/WHU-USI3DV/VistaDream/blob/537aa5c11a68e87491fdc8d8fd7c953928f896df/pipe/refine_mvdps.py#L106)
why choose the first two frames to get loss?

**Comment by HpWang-whu** [comment]
Hi @LiHaodong0217,
The first two frames are the input and outpainted (for scaffold) frames, respectively. We aim to ensure that the optimized multi-view images remain consistent with the input image and global scaffold.

Yours,
